### ISSUE TITLE
TR2 Editor: Off Shot: TR2 will not read the overflow sub-data according to the upper limit.

### ISSUE THREAD

**Issue by HaoJun0823** [HaoJun0823/GECV-OLD#1]
This issue was reported by @QINGYU510

First, let's look at the sub-data structure of TR2:

> According to the number of 0x7C-0x7F, loop to read the following content:
> row_data[row_data_count].offset:int32, these are adjacent addresses. **If any of them exceeds the maximum length of the current data, then this pointer is invalid and should be written as the end of the data to mark it. These pointers may repeat the same address. It is speculated that when the game is compiled, because the data does not need to be modified again, the same data is merged for optimization.**

For example (not related to the game):
Suppose a monster's health has three levels of difficulty:
easy normal hard
0:10 20 30
1:10 10 10
The normal pointer should be:
(cursor)
easy normal hard
01 02 03
11 12 13
Then the pointer of the game content in part of tr2 will be optimized:
(cursor)
easy normal hard
01 02 03
11 11 11
So the data storage will be optimized to:
easy normal hard
0:10 20 30
1:10
This part is re-adjusted to the original appearance in the editor.
easy normal hard
0:10 20 30
1:10 10 10
(cursor)easy normal hard
01 02 03
11 11 11

This change is because the PC version is not a default resource like the early development of PSP, so when I designed the editor, I would automatically add data to align to the array length, otherwise I would optimize.

When we translated off shot, very few tr2s had the above problem.
If you find it, you can use the old version of the tr2 editor, split the tr2 into multiple bins, and modify it manually.

**Comment by HaoJun0823** [comment]
I used to worry that some modders would make multiple different data the same when modifying the game. If I optimize this, the pointer number will be different from the original game, which may cause errors in reading pointers in the original game because the original game has multiple tr2s close together.

So in Off Shot we cannot confirm whether this problem is a problem with tr2 itself or a bug in the game itself.

I will not provide any patches for this problem. Off Shot language translation is not a complicated task (in the rare case of tr2 problems).

**Comment by DarkGD123** [comment]
@nachotacos69

Yamato, better check this out.

**Comment by nachotacos69** [comment]
@DarkGD123 
Never experienced this kind of problem before, plus I don't have a PSVita and a good PC to run vita3k emulator, leaving me with only the PSP at hand to operate these stuff.

**Comment by HaoJun0823** [comment]
This problem seems to be solved, so I don't need to.
